export { default as Home } from "@/pages/Home"
export { default as BookingSinger } from "@/pages/BookingSinger"
export { default as SearchResults } from "@/pages/SearchResults"
export { default as SingerDetails } from "@/pages/SingerDetails"
export { default as SingerProfile } from "@/pages/SingerProfile"